import { getAllContents } from '@/api/ssr';
import Footer from './layout-components/Footer';
import Navbar from './layout-components/Navbar';
import { ContentKey, transformContentsData } from '@/utils';

export const metadata = {
  title: 'Kopalnia żwiru i piasku - Mirosław Makielak',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const { data: contentsData } = await getAllContents();
  const content = transformContentsData(contentsData);

  return (
    <>
      <Navbar />
      <main>{children}</main>
      <Footer
        title={content[ContentKey.FooterTitle]}
        email={content[ContentKey.FooterEmail]}
        phone={content[ContentKey.FooterPhone]}
        address={content[ContentKey.FooterAddress]}
      />
    </>
  );
}
