import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { Montserrat } from 'next/font/google';
import { ToastContainer } from '@/components';

const font = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Kopalnia żwiru i piasku - Mirosław Makielak',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='pl' data-color-mode='light'>
      <body className={`${font.className} bg-neutral-50`}>
        <>
          {children}
          <ToastContainer />
        </>
      </body>
    </html>
  );
}
