export enum ContentKey {
  HomeWelcome = 'HomeWelcome',
  HomeAboutUs = 'HomeAboutUs',
  HomeService1Title = 'HomeService1Title',
  HomeService2Title = 'HomeService2Title',
  HomeService3Title = 'HomeService3Title',
  HomeService1 = 'HomeService1',
  HomeService2 = 'HomeService2',
  HomeService3 = 'HomeService3',
  FooterEmail = 'FooterEmail',
  FooterPhone = 'FooterPhone',
  FooterAddress = 'FooterAddress',
  FooterTitle = 'FooterTitle',
  AboutUsFirst = 'AboutUsFirst',
  AboutUsSecond = 'AboutUsSecond',
  Services = 'Services',
  Contact = 'Contact',
  ContactEmail = 'ContactEmail',
  ContactPhone1 = 'ContactPhone1',
  ContactPhone2 = 'ContactPhone2',
  ContactAddress1 = 'ContactAddress1',
  ContactAddress1Name = 'ContactAddress1Name',
  ContactAddress1Map = 'ContactAddress1Map',
  ContactAddress2 = 'ContactAddress2',
  ContactAddress2Name = 'ContactAddress2Name',
  ContactAddress2Map = 'ContactAddress2Map',
}

export enum ContentImagesKey {
  HomeService1 = 'HomeService1',
  HomeService2 = 'HomeService2',
  HomeService3 = 'HomeService3',
  AboutUs1 = 'AboutUs1',
  AboutUs2 = 'AboutUs2',
  AboutUs3 = 'AboutUs3',
  AboutUs4 = 'AboutUs4',
  Services1 = 'Services1',
  Services2 = 'Services2',
  Services3 = 'Services3',
  Services4 = 'Services4',
}
