export enum Routes {
  Home = '/',
  About_Us = '/onas',
  Offer = '/oferta',
  Services = '/uslugi',
  Certificates = '/certyfikaty',
  Contact = '/kontakt',
  Login = '/auth/login',
  Dashboard = '/admin',
  EditHomePage = '/admin/edit/home',
  EditContactPage = '/admin/edit/contact',
  EditFooter = '/admin/edit/footer',
  EditAbutUsPage = '/admin/edit/about-us',
  EditServicesPage = '/admin/edit/services',
  EditCertificatesPage = '/admin/edit/certificates',
  EditCategories = '/admin/edit/categories',
  EditProducts = '/admin/edit/products',
  DashboardHelp = '/admin/help',
}
